/// A map from a feature string to its score.
///
/// Generated by the `codegen` crate from BudouX's JSON models.
pub type ScoreMap = phf::Map<&'static str, i16>;

/// A BudouX model: the thirteen feature score maps, plus the sum of every
/// score in them.
///
/// The bundled models are built by [`Parser`](crate::Parser)'s constructors,
/// for example [`Parser::japanese_parser`](crate::Parser::japanese_parser).
/// Build this struct yourself to use a custom model with
/// [`Parser::new`](crate::Parser::new).
///
/// Each field name matches the corresponding key in BudouX's JSON models. A
/// boundary sits between the characters at `i - 1` and `i`; the doc comments
/// below describe each feature relative to that boundary.
pub struct Model {
    /// Sum of every score in the maps below. The parser's base score is
    /// `-total_score / 2`, so it must match the maps or the model will split
    /// far too eagerly or not at all.
    pub total_score: i32,
    /// The character 3 positions before the boundary.
    pub uw1: &'static ScoreMap,
    /// The character 2 positions before the boundary.
    pub uw2: &'static ScoreMap,
    /// The character immediately before the boundary.
    pub uw3: &'static ScoreMap,
    /// The character immediately after the boundary.
    pub uw4: &'static ScoreMap,
    /// The character 2 positions after the boundary.
    pub uw5: &'static ScoreMap,
    /// The character 3 positions after the boundary.
    pub uw6: &'static ScoreMap,
    /// The two characters before the boundary.
    pub bw1: &'static ScoreMap,
    /// The two characters straddling the boundary.
    pub bw2: &'static ScoreMap,
    /// The two characters after the boundary.
    pub bw3: &'static ScoreMap,
    /// The three characters before the boundary.
    pub tw1: &'static ScoreMap,
    /// The two characters before and the one after the boundary.
    pub tw2: &'static ScoreMap,
    /// The one character before and the two after the boundary.
    pub tw3: &'static ScoreMap,
    /// The three characters after the boundary.
    pub tw4: &'static ScoreMap,
}
